version: '3'

services:
  server_proxy:
    build:
      context: server_proxy/.
      dockerfile: ../WPCareServerProxy.Dockerfile
    restart: always
    ports:
      - '80:80'
    healthcheck:
      test: ['CMD-SHELL', 'curl --silent --fail localhost:80/health-check || exit 1']
      interval: 300s
      timeout: 10s
      retries: 3
    command: /app/start.sh
