version: '3'

services:
#  server_proxy_dev:
#    build:
#      context: server_proxy/.
#      dockerfile: WPCareServerProxy.Dockerfile
#    environment:
#      - FLASK_SERVER_ADDR=server_api_dev:5000
#    ports:
#      - $WPCARE_PORT:80
#    depends_on:
#      - server_api_dev
#    command: /app/start.sh

  server_api_dev:
    build:
      context: server_api/.
      dockerfile: WPCareServerApi.Dockerfile
    environment:
      FLASK_DEBUG: 1
      FLASK_RUN_PORT: 5000
      PGSQL_WPCARE_HOST: server_data_dev
      PGSQL_WPCARE_DB: ${PGSQL_WPCARE_DB}
      PGSQL_WPCARE_USER: ${PGSQL_WPCARE_USER}
      PGSQL_WPCARE_PASSWORD: ${PGSQL_WPCARE_PASSWORD}
    volumes:
      - ./server_api/src:/home/app/src
    #      - type: bind
    #        source: ./server_api/src
    #        target: /home/app/src
    #        read_only: true
    ports:
      - 5000:5000
    depends_on:
      - server_data_dev
    command: gunicorn --reload --access-logfile '-' -w 1 -t 60 -b 0.0.0.0:5000 src.app:app # flask run --port 5000 --debug

  server_data_dev:
    build:
      context: server_data/.
      dockerfile: WPCareServerData.Dockerfile
      args:
        PGSQL_WPCARE_DB: ${PGSQL_WPCARE_DB}
        PGSQL_WPCARE_USER: ${PGSQL_WPCARE_USER}
        PGSQL_WPCARE_PASSWORD: ${PGSQL_WPCARE_PASSWORD}
        TAG: ${TAG}
    environment:
      POSTGRES_PASSWORD: ${PGSQL_ROOT_PASSWORD}
      POSTGRES_USER: ${PGSQL_ROOT_USER}
    ports:
      - 5432:5432

  server_pycrawl_dev:
    build:
      context: server_pycrawl/.
      dockerfile: WPCareServerPyCrawl.Dockerfile
    environment:
      FLASK_DEBUG: 1
      FLASK_RUN_PORT: 5000
      PGSQL_WPCARE_HOST: server_data_dev
      PGSQL_WPCARE_DB: ${PGSQL_WPCARE_DB}
      PGSQL_WPCARE_USER: ${PGSQL_WPCARE_USER}
      PGSQL_WPCARE_PASSWORD: ${PGSQL_WPCARE_PASSWORD}
    volumes:
      - ./server_pycrawl/src:/home/app/src
    ports:
      - '5005:5005'
    depends_on:
      - server_data_dev
    command: gunicorn --reload --access-logfile '-' -w 1 -t 60 -b 0.0.0.0:5005 src.app:app