version: '3'

services:
  server_proxy_dev:
    build:
      context: server_proxy/.
      dockerfile: WPCareServerProxy.Dockerfile
    environment:
      - FLASK_SERVER_ADDR=server_api:5000
    ports:
      - '80:80'
    depends_on:
      - server_api_dev
    command: /app/start.sh

  server_api_dev:
    build:
      context: server_api/.
      dockerfile: WPCareServerApi.Dockerfile
    environment:
      PGSQL_WPCARE_DB: ${PGSQL_WPCARE_DB}
      PGSQL_WPCARE_USER: ${PGSQL_WPCARE_USER}
      PGSQL_WPCARE_PASSWORD: ${PGSQL_WPCARE_PASSWORD}
    volumes:
      - ./server_api/src:/home/app/src
#      - type: bind
#        source: ./server_api/src
#        target: /home/app/src
#        read_only: true
    ports:
      - '5000:5000'
    depends_on:
      - server_data_dev
    command:  flask run --port 5000 --debug

  server_data_dev:
    build:
      context: server_data/.
      dockerfile: WPCareServerData.Dockerfile
      args:
        PGSQL_WPCARE_DB: ${PGSQL_WPCARE_DB}
        PGSQL_WPCARE_USER: ${PGSQL_WPCARE_USER}
        PGSQL_WPCARE_PASSWORD: ${PGSQL_WPCARE_PASSWORD}
    environment:
      POSTGRES_PASSWORD: ${PGSQL_ROOT_PASSWORD}
      POSTGRES_USER: ${PGSQL_ROOT_USER}
    ports:
      - 5432:5432