
CREATE USER ${PGSQL_WPCARE_USER} WITH LOGIN PASSWORD '${PGSQL_WPCARE_PASSWORD}';
CREATE DATABASE ${PGSQL_WPCARE_DB} OWNER ${PGSQL_WPCARE_USER};

GRANT ALL PRIVILEGES ON DATABASE ${PGSQL_WPCARE_DB} TO ${PGSQL_WPCARE_USER};
